# Generated by Django 5.0.6 on 2024-06-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_category_coupon_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
